### ISSUE TITLE
Link to download latest version points to 0.5.3

### ISSUE THREAD

**Issue by luisdavim** [dcos/dcos-cli#1192]
I was using https://downloads.dcos.io/binaries/cli/darwin/x86-64/latest/ to get the latest binary available and I just found that it's pointing to 0.5.3 instead of the actual latest version

**Comment by ArmandGrillet** [comment]
Thank you for the report. We do not release the latest version of our CLI to that URL anymore, can you tell me if you have seen this URL somewhere in our documentation so that I can edit it?

To download the latest version of our CLI, please use https://downloads.dcos.io/binaries/cli/darwin/x86-64/dcos-1.11/dcos

We might reuse the link https://downloads.dcos.io/binaries/cli/darwin/x86-64/latest/ for our new CLI wrapper, but it's not here yet.

**Comment by Drakan42** [comment]
Just had the same issue with DCOS 1.11 as the install cli commands given to us from the web-ui gives us the https://downloads.dcos.io/binaries/cli/darwin/x86-64/latest/  url to download.

**Comment by ArmandGrillet** [comment]
https://downloads.dcos.io/cli/releases/binaries/dcos/<operating-system>/x86-64/latest/dcos now returns the latest stable CLI version.
