### ISSUE TITLE
ssl_verify bogus

### ISSUE THREAD

**Issue by m0ppers** [dcos/dcos-cli#632]
I might be completely stupid and I am certainly not a python developer but I am currently migrating our dcos subcommand to use the dcos http library (so OAuth is properly working). When doing so I immediately got the following error:

```
$ dcos-arangodb arangodb dbservers
No handlers could be found for logger "dcos.http"
cannot connect to 'xxx/service/arangodb/v1/endpoints.json' An SSL error occurred. To configure your SSL settings, please run: `dcos config set core.ssl_verify <value>`
<value>: Whether to verify SSL certs for HTTPS or path to certs
```

So far so good. I changed the config but the error kept popping up.

After checking the source it seems to me that the flag is in fact never used. Instead the environment variable `DCOS_SSL_VERIFY` is the one controlling the behaviour. Unless I am mistaken (which is totally possible) the ssl_verify flag is bogus and should either be removed (including the misleading error message) or properly implemented

**Comment by tamarrow** [comment]
The `ssl_verify` config value gets set as an env variable in `set_ssl_info_env_vars` in `cli/dcoscli/main.py`. And then in `dcos/http` we just look for the env variable. However, since you are using the `dcos/http` library and not going through dcos-cli main, the config value is not working. Will fix.
